<a href="https://colab.research.google.com/github/LDSoul/KaggleProblem/blob/master/Kaggle%E5%AF%A6%E4%BD%9C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
spam_amount = 0
print(spam_amount)

spam_amount +=4

if spam_amount > 0:
  print("But I dont want ANY spam!")

viking_song = "Spam " * spam_amount
print(viking_song)

0
But I dont want ANY spam!
Spam Spam Spam Spam 


In [ ]:
spam_amount = 0
type(spam_amount)
type(19.95)

float

In [ ]:
print(5/2)
print(6/2)

2.5
3.0


In [ ]:
# // 4捨5入
print(5 // 2)
print(13 // 3)

2
4


In [ ]:
print(min(1,2,3))
print(max(1,2,3))

1
3


In [ ]:
print(abs(32))
print(abs(-32))

32
32


In [ ]:
print(float(10))
print(int(3.33))
print(int('807')+1)

10.0
3
808


 =====Function=====

In [ ]:
help(round(-2.01))

In [ ]:
def least_difference(a,b,c):
  diff1 = abs(a-b)
  diff2 = abs(b-c)
  diff3 = abs(a-c)
  return min(diff1,diff2,diff3)

In [ ]:
print(
    least_difference(1,10,100),
    least_difference(1,10,10),
    least_difference(5,6,7),
)

9 0 1


help(least_difference)

In [ ]:
def least_difference(a,b,c):
  diff1 = abs(a-b)
  diff2 = abs(b-c)
  diff3 = abs(a-c)
  min(diff1,diff2,diff3)

print(
    least_difference(1,10,100),
    least_difference(1,10,10),
    least_difference(5,6,7),
)

None None None


In [ ]:
mystery = print()
print(mystery)


None


In [ ]:
print(1,2,3,sep=' < ')

1 < 2 < 3


In [ ]:
print(1,2,3)

1 2 3


In [ ]:
def greet(who="Colin"):
  print("Hello,",who)

greet() #不用參數時 who=Colin
greet(who="kaggle") #更改參數時 who改為Kaggle
greet("world") #也可以不打who 直接""也能改
greet() #反正不打參數直接括號 就是方法裡面多少就多少

Hello, Colin
Hello, kaggle
Hello, world
Hello, Colin


In [ ]:
def mult_by_five(x):
    return 5 * x

def call(fn, arg):
    """Call fn on arg"""
    return fn(arg)

def squared_call(fn, arg):
    """Call fn on the result of calling fn on arg"""
    return fn(fn(arg))

print(
    call(mult_by_five, 1),  #fn為5*x函數 x=1帶入
    squared_call(mult_by_five, 1), #fn為5*x函數 在括號一層fn = (5*x) * (5*x)
    sep='\n', # '\n' is the newline character - it starts a new line
)

5
25


In [ ]:
def mod_5(x):
    """Return the remainder of x after dividing by 5"""
    return x % 5

print(
    'Which number is biggest?',
    max(100, 51, 14),
    'Which number is the biggest modulo 5?',
    min(100, 16, 14, key=mod_5), #三個數值 帶入key=mod_5的方法 在比較誰最小
    sep='\n',
)

Which number is biggest?
100
Which number is the biggest modulo 5?
100


In [ ]:
x = True
print(x)
print(type(x))

True
<class 'bool'>


In [ ]:
def can_run_for_president(age):
  return age>=35
print("Can a 19 year old?", can_run_for_president(19))
print("Can a 45 year old?", can_run_for_president(45))

Can a 19 year old? False
Can a 45 year old? True


In [ ]:
3.0 == 3

True

In [ ]:
'3' == 3

False

In [ ]:
def is_odd(n):
  return (n % 2) == 1

print("100 is odd?",is_odd(100))
print("-1 is odd?", is_odd(-1))

100 is odd? False
-1 is odd? True


In [ ]:
def can_run_for_president(age, is_natural_born_citizen):
  return is_natural_born_citizen and (age >= 35)  

print(can_run_for_president(19,True))
print(can_run_for_president(55,False))
print(can_run_for_president(55,True))

False
False
True


In [ ]:
True or True and False  #python優先順序:Not -> And -> Or

True

In [ ]:
def inspect(x):
    if x == 0:
        print(x, "is zero")
    elif x > 0:
        print(x, "is positive")
    elif x < 0:
        print(x, "is negative")
    else:
        print(x, "is unlike anything I've ever seen...")
inspect(0)
inspect(-15)

0 is zero
-15 is negative


In [ ]:
def f(x):
    if x > 0:
        print("Only printed when x is positive; x =", x)
        print("Also only printed when x is positive; x =", x)
    print("Always printed, regardless of x's value; x =", x)

f(1)
f(0)

Only printed when x is positive; x = 1
Also only printed when x is positive; x = 1
Always printed, regardless of x's value; x = 1
Always printed, regardless of x's value; x = 0


In [ ]:
print(bool(1)) # all numbers are treated as true, except 0
print(bool(0))
print(bool("asf")) # all strings are treated as true, except the empty string ""
print(bool(""))

True
False
True
False


In [ ]:
if 0:
    print(0)
elif "spam":
    print("spam")

spam


=====Lists=====

In [ ]:
primes = [2,3,5,7]
planets = ['Mercury','Venus','Earth','Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
hands = [
  ['J','Q','K'],
  ['2','2','2'],
  ['6','A','K'],
]
hands = [['J', 'Q', 'K'], ['2', '2', '2'], ['6', 'A', 'K']]

#==Index
planets[0]
#Mercury

planets[1]
#Venus

planets[-1]
#Neptune

planets[-2] #負號會在到回推
#Uranus

#==Slicing
planets[0:3]
#planets 0~(3-1)的資料
#['Mercury', 'Venus', 'Earth']

planets[:3] #前三筆資料
#['Mercury', 'Venus', 'Earth']

planets[3:] #後三筆資料
#['Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']


#==Changing lists
planets[3] = 'Malacandra' #更改lists內的值
planets
#['Mercury','Venus','Earth','Malacandra','Jupiter','Saturn','Uranus','Neptune']


#==List function
len(planets) #lists的長度
#8

#sort 照字母排序
sorted(planets)
#['Earth','Jupiter','Malacandra','Mercury','Neptune','Saturn','Uranus','Venus']

#sum
primes = [2,3,5,7]
sum(primes) #直接將primes內的所有值相加
#17

#max
max(primes) #最大值
#7

#==Interlude:objects
x = 12
print(x.imag)
# x is a real number, so its imaginary part is 0.

c = 12+3j
print(c.imag)
# Here's how to make a complex number, in case you've ever been curious:3.0

x.bit_length
#<function int.bit_length>

x.bit_length()
#4

#help(x.bit_length)

#==List methods
planets.append('Pluto') #新增一筆資料

#pop
planets.pop() #pop出來

planets #查看

#==Searching lists
planets.index('Earth') #Earth在陣列第幾位置
#2

#in ???
"Earth" in planets #Earth是否在planets裡面
#True

"BTS" in planets
#False

#==Tuples
t = (1,2,3)
t = 1,2,3
t

#t[0] = 100 #這是錯的

x = 0.125
x.as_integer_ratio() #返回分子和分母
#(1,8) 1/8-0.125

numerator, denominator = x.as_integer_ratio() #前者為1 後者為8
print(numerator / denominator)
#0.125

a=1
b=0
a,b = b,a #a b值互換
print(a,b)

0
3.0
0.125
0 1


=====Loops=====

In [ ]:
planets = ['ad', 'bd', 'Cd', 'Dd', 'dE', 'dFVRVAas', 'aG', 'aH']
for i in planets:
  print(i, end='') #i到planets 全輸出
#ABCDEFGH

m = (2,2,2,3,3,5)
p = 1
for n in m:
  p *= n
print(p)
#360

s = 'steganograpHy is the practicE of conceaLing a file, message, image, or video within another fiLe, message, image, Or video.'
msg = ''
# print all the uppercase letters in s, one at a time
for char in s:
    if char.isupper(): #判斷字元是否為大寫
        print(char, end='') #大寫就輸出
#HELLO

#==range
for i in range(5):
  print("Doing important work. i =",i)

#==while loop
i=0
while i<10:
  print(i,end=' ')
  i+=1
#0 1 2 3 4 5 6 7 8 9

#==List comprehensions
s = [n**2 for n in range(10)]
s
#0 1 4 9 16 25 36 49 64 81

s =[]
for n in range(10):
  s.append(n**2)
s 
#0 1 4 9 16 25 36 49 64 81

s_p = [planet for planet in planets if len(planet)<3] #只輸出長度小於3
s_p

loud_short_planets = [planet.upper() + '!' for planet in planets if len(planet) < 6] #全轉大寫 長度小於6輸出
loud_short_planets

def count_negatives(nums):
    """Return the number of negative numbers in the given list.
    
    >>> count_negatives([5, -1, -2, 0, 3])
    2
    """
    n_negative = 0
    for num in nums:
        if num < 0:
            n_negative = n_negative + 1
    return n_negative
    
def count_negatives(nums):
    return len([num for num in nums if num < 0])

def count_negatives(nums):
    # Reminder: in the "booleans and conditionals" exercises, we learned about a quirk of 
    # Python where it calculates something like True + True + False + True to be equal to 3.
    return sum([num < 0 for num in nums])


adbdCdDddEdFVRVAasaGaH360
HELLODoing important work. i = 0
Doing important work. i = 1
Doing important work. i = 2
Doing important work. i = 3
Doing important work. i = 4
0 1 2 3 4 5 6 7 8 9 

=====Strings=====

In [ ]:
x = 'Sssddds'
y = "Sssddds"
x == y
#True

print('Sssddd\'s') #若要' 則前面則須加上\
#規則 \   '
#     \\  \
#     \n  跳行

hello = "hello\nworld"
print(hello)

trip_hello = """hello
world"""
print(trip_hello)
trip_hello == hello

Sssddd's
hello
world
hello
world


True

In [ ]:
print("hello")
print("world")
print("hello",end='')
print("pluto",end='')

hello
world
hellopluto

In [ ]:
planet = 'Pluto' 
planet[0] #元素內的值無法改變 planet[0] = 'B' 這會出錯

'P'

In [ ]:
planet[-3:]

'uto'

In [ ]:
len(planet)

5

In [ ]:
[char+'! ' for char in planet]

['P! ', 'l! ', 'u! ', 't! ', 'o! ']

In [ ]:
c = "Pluto is a Planet"
print(c.upper()) #轉大寫
print(c.lower()) #轉小寫 
print(c.index('Plan')) #陣列第幾個位置

PLUTO IS A PLANET
pluto is a planet
11


In [ ]:
c.startswith(planet) #判斷此字串是否在指定字元開頭

True

In [ ]:
c.endswith('dwarf planet') #查看結尾是否有出現此字串

False

In [ ]:
words = c.split() #切空格
words

['Pluto', 'is', 'a', 'Planet']

In [ ]:
datestr = '1956-01-31'
year,month,day = datestr.split('-')
'/'.join([month,day,year])

'01/31/1956'

In [ ]:
' 👏 '.join([word.upper() for word in words])

'PLUTO 👏 IS 👏 A 👏 PLANET'

In [ ]:
planet = 'Pluto'
planet + ', we miss you.'

'Pluto, we miss you.'

In [ ]:
p = 9
planet + ", you'll always be the " + str(p) + "th planet to me." #int轉型String

"Pluto, you'll always be the 9th planet to me."

In [ ]:
"{}, you'll always be the {}th planet to me.".format(planet, p) #format格式

"Pluto, you'll always be the 9th planet to me."

In [ ]:
pluto_mass = 1.303 * 10**22
earth_mass = 5.9722 * 10**24
population = 52910390
"{} weighs about {:.2} kilograms ({:.3%} of Earth's mass). It is home to {:,} Plutonians.".format(
    planet, pluto_mass, pluto_mass / earth_mass, population,
)
#不一定要用STR轉 可直接用Format

"Pluto weighs about 1.3e+22 kilograms (0.218% of Earth's mass). It is home to 52,910,390 Plutonians."

In [ ]:
s = """Pluto's a {0}.
No, it's a {1}.
{0}!
{1}!""".format('planet','dwarf planet')
print(s)

Pluto's a planet.
No, it's a dwarf planet.
planet!
dwarf planet!


In [ ]:
number = {'one':1,'two':2,'three':3}
number['one']

1

In [ ]:
number['eleven'] = 11 #新增

{'eleven': 11, 'one': 1, 'three': 3, 'two': 2}

In [ ]:
number['one'] = 'Pluto' #改變
number

{'eleven': 11, 'one': 'Pluto', 'three': 3, 'two': 2}

In [ ]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
planet_to_initial = {planet: planet[0] for planet in planets}
planet_to_initial

{'Earth': 'E',
 'Jupiter': 'J',
 'Mars': 'M',
 'Mercury': 'M',
 'Neptune': 'N',
 'Saturn': 'S',
 'Uranus': 'U',
 'Venus': 'V'}

In [ ]:
'Saturn' in planet_to_initial

True

In [ ]:
'Betelgeuse' in planet_to_initial

False

In [ ]:
for k in number:
    print("{} = {}".format(k, number[k]))

one = Pluto
two = 2
three = 3
eleven = 11


In [ ]:
' '.join(sorted(planet_to_initial.values())) #字母排序

'E J M M N S U V'

In [ ]:
for planet, initial in planet_to_initial.items():
    print("{} begins with \"{}\"".format(planet.rjust(10), initial))

   Mercury begins with "M"
     Venus begins with "V"
     Earth begins with "E"
      Mars begins with "M"
   Jupiter begins with "J"
    Saturn begins with "S"
    Uranus begins with "U"
   Neptune begins with "N"


=====Imports=====


In [ ]:
import math
print("it is math! it has type{}".format(type(math)))

it is math! it has type<class 'module'>


In [ ]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [ ]:
print("pi to 4 = {:.4}".format(math.pi))

pi to 4 = 3.142


In [ ]:
math.log(32,2)

5.0

In [ ]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x[, base])
    
    Return the logarithm of x to the given base.
    If the base not specified, returns the natural logarithm (base e) of x.



In [ ]:
import math as mt
mt.pi

3.141592653589793

In [ ]:
from math import *
print(pi,log(32,2))

3.141592653589793 5.0


In [ ]:
from math import log,pi
from numpy import asarray
print(pi,log(32,2))

3.141592653589793 5.0


In [ ]:
import numpy
print("numpy random is a",type(numpy.random))
print("it contains names such as...0",dir(numpy.random)[-15:])

numpy random is a <class 'module'>
it contains names such as...0 ['seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [ ]:
rolls = numpy.random.randint(low=1,high=6,size=10) #亂數1~5 10個
rolls

array([3, 2, 2, 4, 3, 5, 2, 2, 1, 1])

In [ ]:
type(rolls)

numpy.ndarray

In [ ]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [ ]:
rolls.mean() #骰子均值?

2.5

In [ ]:
rolls.tolist()

[3, 2, 2, 4, 3, 5, 2, 2, 1, 1]

In [ ]:
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [ ]:
help(rolls)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [ ]:
rolls + 10 #每個數值+10

array([13, 12, 12, 14, 13, 15, 12, 12, 11, 11])

In [ ]:
rolls <= 3 #<=3的判斷

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True])

In [ ]:
xlist = [[1,2,3],[2,4,6],]
x = numpy.asarray(xlist) #建立一二維矩陣
print("xlist = {}\nx =\n{}".format(xlist,x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [ ]:
x[1,-1]

6

In [ ]:
import tensorflow as tf
a = tf.constant(1)
b = tf.constant(1)
a + b

<tf.Tensor: shape=(), dtype=int32, numpy=2>